version: "3"
services:
  postman-newman-framework:
    image: node:14.16.0
    volumes:
      - ./:/tmp/postman-newman-framework
      - /var/tmp/:/var/tmp/
    container_name: postman-newman-framework
    working_dir: /tmp/postman-newman-framework
    command: bash -c "npm install && npm run test"